/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Conexao;
import dao.EscopoDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Escopo;
/**
 *
 * @author Administrador
 */
public class FormEscopo extends javax.swing.JFrame {

    /**
     * Creates new form FormCadastrosolucoes
     */
    public FormEscopo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbox1 = new java.awt.Checkbox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jCheckBoxvox = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldcnpj = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldnomeempresa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldentregaveispossi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldobjetivoneg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldentregavelmin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();

        checkbox1.setLabel("checkbox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Solução/Produto  ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("CORE: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox1.setText("Pricing");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));
        jCheckBox1.setVisible(false);
        if (jCheckBox1.isSelected())
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox3.setText("Marketing & Planning");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));
        jCheckBox3.setVisible(false);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox2.setText("S3");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, -1, 30));

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox4.setText("Sales & Distribution");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));
        jCheckBox4.setVisible(false);

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox5.setText("Matching & Risk");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));
        jCheckBox5.setVisible(false);

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox6.setText("Optimization ");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));
        jCheckBox6.setVisible(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SEGUINTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 630, 180, 60));

        jCheckBoxvox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBoxvox.setText("Vox");
        jCheckBoxvox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxvoxActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxvox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));
        jCheckBoxvox.setVisible(false);

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox8.setText("Web app ");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        jCheckBox9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox9.setText("API gateway ");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, -1, -1));

        jCheckBox10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox10.setText("Filas ");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, -1, -1));

        jCheckBox11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox11.setText("Step function ");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        jCheckBox12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox12.setText("Cloudwatch");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, -1, 30));

        jCheckBox13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox13.setText("Fargate ");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, 30));

        jCheckBox14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox14.setText("Containers");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, -1, 30));

        jCheckBox15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox15.setText("lambda ");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, 30));

        jCheckBox16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox16.setText("Painéis Gráficos e Relatórios");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, -1, 30));

        jCheckBox17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox17.setText("Parquet");
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, -1, 30));

        jCheckBox18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox18.setText("Quicksight");
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, -1, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar Solução", "Nxt.Demand", "Nxt.Operations" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 190, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/MicrosoftTeams-image (17).png"))); // NOI18N
        jLabel4.setPreferredSize(getMaximumSize());
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("CNPJ: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        getContentPane().add(jTextFieldcnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 330, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Nome da Empresa: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));
        getContentPane().add(jTextFieldnomeempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 410, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Volume:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, -1, 30));
        jLabel8.setVisible(false);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 240, 30));
        jTextField3.setVisible(false);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 100, 30));
        jTextField4.setVisible(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Funcionalidades ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, -1, -1));

        jCheckBox19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox19.setText("Mongodb");
        jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox19ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, -1, 30));

        jCheckBox20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox20.setText("Gerador de Data Lake ");
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, -1, 30));

        jCheckBox21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox21.setText("Busca por LNP");
        jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, -1, 30));

        jCheckBox22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox22.setText("Ingestão Automatizada ");
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Entregáveis Possíveis ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));
        getContentPane().add(jTextFieldentregaveispossi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 220, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Objetivo do Negócio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));
        getContentPane().add(jTextFieldobjetivoneg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 220, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Entregável Mínimo ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));
        getContentPane().add(jTextFieldentregavelmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 220, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Estrutura de Dados mínimos:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, 30));
        jLabel11.setVisible(false);
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 100, 30));
        jTextField12.setVisible(false);
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 100, 30));
        jTextField13.setVisible(false);
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 240, 30));
        jTextField14.setVisible(false);
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 240, 30));
        jTextField15.setVisible(false);
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 240, 30));
        jTextField16.setVisible(false);
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 240, 30));
        jTextField17.setVisible(false);
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 100, 30));
        jTextField18.setVisible(false);
        getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 100, 30));
        jTextField19.setVisible(false);
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 100, 30));
        jTextField20.setVisible(false);

        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 240, 30));
        jTextField22.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBoxvoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxvoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxvoxActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       String cnpj = jTextFieldcnpj.getText();
       String nome_empresa = jTextFieldnomeempresa.getText();
       String objetivo_neg = jTextFieldobjetivoneg.getText();
       String entregavel_min = jTextFieldentregavelmin.getText();
       String entregaveis_possi = jTextFieldentregaveispossi.getText();
       String funcionalidade = "";
        if (jCheckBox20.isSelected())
            funcionalidade+="Gerador de DataLake; ";
        if (jCheckBox21.isSelected())
            funcionalidade+="Busca por LNP; ";
        if (jCheckBox22.isSelected())
            funcionalidade+="Ingestão Automatizada; ";
        if (jCheckBox16.isSelected())
            funcionalidade+="Painéis, gráficos e relatórios; ";
       
       String estrutura_min_vox =  jTextField15.getText();
       String volume_vox =  jTextField18.getText();
       
       String estrutura_min_mktEplan =  jTextField17.getText();
       String volume_mktEplan =  jTextField12.getText();
       
       String estrutura_min_sales =  jTextField16.getText();
       String volume_sales =  jTextField13.getText();
       
       String estrutura_min_pricing =  jTextField3.getText();
       String volume_pricing =  jTextField4.getText();
       
       String estrutura_min_optimization =  jTextField14.getText();
       String volume_optimization =  jTextField19.getText();
       
       String estrutura_min_matching =  jTextField22.getText();
       String volume_matching =  jTextField20.getText();
       
       String solucao = (String)jComboBox1.getSelectedItem();
        
       String produto = "";
        if (jCheckBoxvox.isSelected())
            produto+="Vox; ";
        if (jCheckBox3.isSelected())
            produto+="Marketing&Planning; ";
        if (jCheckBox4.isSelected())
            produto+="Sales&Distribution; ";
        if (jCheckBox1.isSelected())
            produto+="Pricing; ";
        
        if (jCheckBox6.isSelected())
            produto+="Optimization; ";
        if (jCheckBox5.isSelected())
            produto+="Matching&Risk; ";
        
       String core = "";
        if (jCheckBox8.isSelected())
            core+="Web App; ";
        if (jCheckBox9.isSelected())
            core+="API Gateway; ";
        if (jCheckBox10.isSelected())
            core+="Filas; ";
        if (jCheckBox11.isSelected())
            core+="Step Function; ";
        if (jCheckBox15.isSelected())
            core+="Lambda; ";
        if (jCheckBox13.isSelected())
            core+="Fargate; ";
        if (jCheckBox14.isSelected())
            core+="Containers; ";
        if (jCheckBox2.isSelected())
            core+="S3; ";
        if (jCheckBox16.isSelected())
            core+="MongoDB; ";
        if (jCheckBox17.isSelected())
            core+="Parquet; ";
        if (jCheckBox18.isSelected())
            core+="QuickSight; ";
        if (jCheckBox12.isSelected())
            core+="CloudWatch; ";
        
        
        Escopo usuarioluiz = new Escopo(cnpj, nome_empresa, objetivo_neg, entregavel_min, entregaveis_possi, solucao, produto, funcionalidade, 
                core, estrutura_min_vox, volume_vox, estrutura_min_mktEplan, volume_mktEplan, estrutura_min_sales, volume_sales, estrutura_min_pricing, 
                volume_pricing, estrutura_min_optimization, volume_optimization, estrutura_min_matching, volume_matching);
        
        try {
            Connection conexao = new Conexao().getConnection();
            EscopoDAO cadastro = new EscopoDAO(conexao);
            cadastro.insert(usuarioluiz);
        
        } catch (SQLException ex) {
            Logger.getLogger(FormEscopo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        FormBronze telaDecadastro = new FormBronze();
        telaDecadastro.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     String solucao = (String)jComboBox1.getSelectedItem();
        if(solucao.equals("Selecionar Solução")){
            jCheckBoxvox.setVisible(false);
            jCheckBox3.setVisible(false);
            jCheckBox4.setVisible(false);
            jCheckBox1.setVisible(false);
            jCheckBox6.setVisible(false);
            jCheckBox5.setVisible(false);
            
            jLabel11.setVisible(false);
            jLabel8.setVisible(false);
            
            jTextField15.setVisible(false);
            jTextField17.setVisible(false);
            jTextField16.setVisible(false);
            jTextField3.setVisible(false);
            jTextField18.setVisible(false);
            jTextField12.setVisible(false);
            jTextField13.setVisible(false);
            jTextField4.setVisible(false);
            jTextField14.setVisible(false);
            jTextField22.setVisible(false);
            jTextField19.setVisible(false);
            jTextField20.setVisible(false);
    }
        if(solucao.equals("Nxt.Demand")){
            jCheckBox6.setVisible(false);
            jCheckBox5.setVisible(false);
            jCheckBoxvox.setVisible(true);
            jCheckBox3.setVisible(true);
            jCheckBox4.setVisible(true);
            jCheckBox1.setVisible(true);
            jLabel8.setVisible(true);
            jLabel11.setVisible(true);
            jTextField15.setVisible(true);
            jTextField17.setVisible(true);
            jTextField16.setVisible(true);
            jTextField3.setVisible(true);
            jTextField18.setVisible(true);
            jTextField12.setVisible(true);
            jTextField13.setVisible(true);
            jTextField4.setVisible(true);
            jTextField14.setVisible(false);
            jTextField22.setVisible(false);
            jTextField19.setVisible(false);
            jTextField20.setVisible(false);
            
        
            
    }
        if(solucao.equals("Nxt.Operations")){
            jCheckBoxvox.setVisible(false);
            jCheckBox3.setVisible(false);
            jCheckBox4.setVisible(false);
            jCheckBox1.setVisible(false);
            jCheckBox6.setVisible(true);
            jCheckBox5.setVisible(true);
            jLabel8.setVisible(true);
            jLabel11.setVisible(true);
            jTextField14.setVisible(true);
            jTextField22.setVisible(true);
            jTextField19.setVisible(true);
            jTextField20.setVisible(true);
            jTextField15.setVisible(false);
            jTextField17.setVisible(false);
            jTextField16.setVisible(false);
            jTextField3.setVisible(false);
            jTextField18.setVisible(false);
            jTextField12.setVisible(false);
            jTextField13.setVisible(false);
            jTextField4.setVisible(false);
    }
    
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox19ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox21ActionPerformed

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox22ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEscopo().setVisible(true);
                
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JCheckBox jCheckBoxvox;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldcnpj;
    private javax.swing.JTextField jTextFieldentregaveispossi;
    private javax.swing.JTextField jTextFieldentregavelmin;
    private javax.swing.JTextField jTextFieldnomeempresa;
    private javax.swing.JTextField jTextFieldobjetivoneg;
    // End of variables declaration//GEN-END:variables
}
