/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.BronzeDAO;
import dao.Conexao;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Bronze;

/**
 *
 * @author Administrador
 */
public class FormBronze extends javax.swing.JFrame {

    /**
     * Creates new form FormCadastroTela2
     */
    public FormBronze() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBoxERP = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jCheckBoxjson = new javax.swing.JCheckBox();
        jCheckBoxplanilhas = new javax.swing.JCheckBox();
        jCheckBoxtexto = new javax.swing.JCheckBox();
        jCheckBoxtabelas = new javax.swing.JCheckBox();
        jCheckBoxcsv = new javax.swing.JCheckBox();
        jCheckBoxaudio = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jCheckBoxvendas = new javax.swing.JCheckBox();
        jCheckBoxoutros = new javax.swing.JCheckBox();
        jCheckBoxpdf = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jTxtvolumetexto = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTxtvolumecsv = new javax.swing.JTextField();
        jTxtvolumeplanilhas = new javax.swing.JTextField();
        jTxtvolumetabelas = new javax.swing.JTextField();
        jTxtvolumepdf = new javax.swing.JTextField();
        jTxtvolumeaudio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtvolumejson = new javax.swing.JTextField();
        jTxtfreqjson = new javax.swing.JTextField();
        jTxtfreqcsv = new javax.swing.JTextField();
        jTxtfreqplanilhas = new javax.swing.JTextField();
        jTxtfreqtexto = new javax.swing.JTextField();
        jTxtfreqtabelas = new javax.swing.JTextField();
        jTxtfreqpdf = new javax.swing.JTextField();
        jTxtfreqaudio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Sistemas: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, -1, -1));

        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setText("SALVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 610, 180, 40));

        jCheckBoxERP.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxERP.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jCheckBoxERP.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBoxERP.setText("ERP");
        jCheckBoxERP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxERPActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxERP, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Frequência:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));
        jLabel9.setVisible(false);

        jCheckBoxjson.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxjson.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jCheckBoxjson.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBoxjson.setText("JSON");
        jCheckBoxjson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxjsonActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxjson, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jCheckBoxplanilhas.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxplanilhas.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jCheckBoxplanilhas.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBoxplanilhas.setText("PLANILHAS");
        jCheckBoxplanilhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxplanilhasActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxplanilhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jCheckBoxtexto.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxtexto.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jCheckBoxtexto.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBoxtexto.setText("TEXTO");
        jCheckBoxtexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxtextoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxtexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, -1));

        jCheckBoxtabelas.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxtabelas.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jCheckBoxtabelas.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBoxtabelas.setText("TABELAS");
        jCheckBoxtabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxtabelasActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxtabelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jCheckBoxcsv.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxcsv.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jCheckBoxcsv.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBoxcsv.setText("CSV");
        jCheckBoxcsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxcsvActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxcsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jCheckBoxaudio.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxaudio.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jCheckBoxaudio.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBoxaudio.setText("AUDIO");
        jCheckBoxaudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxaudioActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxaudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Formato: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jCheckBoxvendas.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxvendas.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jCheckBoxvendas.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBoxvendas.setText("VENDAS");
        jCheckBoxvendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxvendasActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxvendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, -1, -1));

        jCheckBoxoutros.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxoutros.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jCheckBoxoutros.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBoxoutros.setText("OUTROS");
        jCheckBoxoutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxoutrosActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxoutros, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, -1, -1));

        jCheckBoxpdf.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBoxpdf.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jCheckBoxpdf.setForeground(new java.awt.Color(240, 240, 240));
        jCheckBoxpdf.setText("PDF");
        jCheckBoxpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxpdfActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxpdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Origem do dado: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));
        getContentPane().add(jTxtvolumetexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 170, 30));
        jTxtvolumetexto.setVisible(false);

        jComboBox1.setBackground(new java.awt.Color(240, 240, 240));
        jComboBox1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar", "API", "SFTP", "Upload" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 370, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 370, 190, 30));
        jTextField1.setVisible(false);
        getContentPane().add(jTxtvolumecsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 170, 30));
        jTxtvolumecsv.setVisible(false);
        getContentPane().add(jTxtvolumeplanilhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 170, 30));
        jTxtvolumeplanilhas.setVisible(false);
        getContentPane().add(jTxtvolumetabelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 170, 30));
        jTxtvolumetabelas.setVisible(false);
        getContentPane().add(jTxtvolumepdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 170, 30));
        jTxtvolumepdf.setVisible(false);
        getContentPane().add(jTxtvolumeaudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 170, 30));
        jTxtvolumeaudio.setVisible(false);

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Volume:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));
        jLabel10.setVisible(false);
        getContentPane().add(jTxtvolumejson, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 170, 30));
        jTxtvolumejson.setVisible(false);
        getContentPane().add(jTxtfreqjson, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 310, 30));
        jTxtfreqjson.setVisible(false);
        getContentPane().add(jTxtfreqcsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 310, 30));
        jTxtfreqcsv.setVisible(false);
        getContentPane().add(jTxtfreqplanilhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 310, 30));
        jTxtfreqplanilhas.setVisible(false);
        getContentPane().add(jTxtfreqtexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 310, 30));
        jTxtfreqtexto.setVisible(false);
        getContentPane().add(jTxtfreqtabelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 310, 30));
        jTxtfreqtabelas.setVisible(false);
        getContentPane().add(jTxtfreqpdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 310, 30));
        jTxtfreqpdf.setVisible(false);
        getContentPane().add(jTxtfreqaudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 310, 30));
        jTxtfreqaudio.setVisible(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/1080.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxERPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxERPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxERPActionPerformed

    private void jCheckBoxjsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxjsonActionPerformed
    if (jCheckBoxjson.isSelected()){
        jTxtvolumejson.setVisible(true); jTxtfreqjson.setVisible(true); jLabel9.setVisible(true); jLabel10.setVisible(true);}
    else {jTxtvolumejson.setVisible(false); jTxtfreqjson.setVisible(false);}

    }//GEN-LAST:event_jCheckBoxjsonActionPerformed

    private void jCheckBoxplanilhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxplanilhasActionPerformed
    if (jCheckBoxplanilhas.isSelected()){
        jTxtvolumeplanilhas.setVisible(true); jTxtfreqplanilhas.setVisible(true); jLabel9.setVisible(true); jLabel10.setVisible(true);}
    else {jTxtvolumeplanilhas.setVisible(false); jTxtfreqplanilhas.setVisible(false);} 
    }//GEN-LAST:event_jCheckBoxplanilhasActionPerformed

    private void jCheckBoxtextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxtextoActionPerformed
    if (jCheckBoxtexto.isSelected()){
        jTxtvolumetexto.setVisible(true); jTxtfreqtexto.setVisible(true); jLabel9.setVisible(true); jLabel10.setVisible(true);}
    else {jTxtvolumetexto.setVisible(false); jTxtfreqtexto.setVisible(false);}
    }//GEN-LAST:event_jCheckBoxtextoActionPerformed

    private void jCheckBoxtabelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxtabelasActionPerformed
    if (jCheckBoxtabelas.isSelected()){
        jTxtvolumetabelas.setVisible(true); jTxtfreqtabelas.setVisible(true); jLabel9.setVisible(true); jLabel10.setVisible(true);}
    else {jTxtvolumetabelas.setVisible(false); jTxtfreqtabelas.setVisible(false);}
    }//GEN-LAST:event_jCheckBoxtabelasActionPerformed

    private void jCheckBoxcsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxcsvActionPerformed
    if (jCheckBoxcsv.isSelected()){
        jTxtvolumecsv.setVisible(true); jTxtfreqcsv.setVisible(true); jLabel9.setVisible(true); jLabel10.setVisible(true);}
    else {jTxtvolumecsv.setVisible(false); jTxtfreqcsv.setVisible(false);}
    }//GEN-LAST:event_jCheckBoxcsvActionPerformed

    private void jCheckBoxaudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxaudioActionPerformed
    if (jCheckBoxaudio.isSelected()){
        jTxtvolumeaudio.setVisible(true); jTxtfreqaudio.setVisible(true); jLabel9.setVisible(true); jLabel10.setVisible(true);}
    else {jTxtvolumeaudio.setVisible(false); jTxtfreqaudio.setVisible(false);}
    }//GEN-LAST:event_jCheckBoxaudioActionPerformed

    private void jCheckBoxvendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxvendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxvendasActionPerformed

    private void jCheckBoxoutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxoutrosActionPerformed

        if(jCheckBoxoutros.isSelected())
            jTextField1.setVisible(true);
        else jTextField1.setVisible(false);
    }//GEN-LAST:event_jCheckBoxoutrosActionPerformed

    private void jCheckBoxpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxpdfActionPerformed
    if (jCheckBoxpdf.isSelected()){
        jTxtvolumepdf.setVisible(true); jTxtfreqpdf.setVisible(true); jLabel9.setVisible(true); jLabel10.setVisible(true);}
    else {jTxtvolumepdf.setVisible(false); jTxtfreqpdf.setVisible(false);}
    }//GEN-LAST:event_jCheckBoxpdfActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String origem = (String)jComboBox1.getSelectedItem();
    String formato = "";
        if(jCheckBoxjson.isSelected())
            formato+="JSON; ";
        if(jCheckBoxcsv.isSelected())
            formato+="CSV; ";
        if(jCheckBoxplanilhas.isSelected())
            formato+="Planilhas; ";
        if(jCheckBoxtabelas.isSelected())
            formato+="Tabelas; ";
        if(jCheckBoxpdf.isSelected())
            formato+="PDF; ";
        if(jCheckBoxaudio.isSelected())
            formato+="Audio; ";
        if(jCheckBoxtexto.isSelected())
            formato+="Texto; ";
        
    String sistema = "";
        if(jCheckBoxERP.isSelected())
            sistema+="ERP; ";
        if(jCheckBoxvendas.isSelected())
            sistema+="Vendas; ";
        if(jCheckBoxoutros.isSelected())
            sistema+=jTextField1.getText();
        
    String volume_json = "";
        if(jCheckBoxjson.isSelected())
            volume_json+=jTxtvolumejson.getText();
    String freq_json = "";
        if(jCheckBoxjson.isSelected())
            freq_json+= jTxtfreqjson.getText();
        
    String volume_csv = "";
        if(jCheckBoxcsv.isSelected())
            volume_csv+=jTxtvolumecsv.getText();
    String freq_csv = "";
        if(jCheckBoxcsv.isSelected())
            freq_csv+= jTxtfreqcsv.getText();
        
    String volume_planilhas = "";
        if(jCheckBoxplanilhas.isSelected())
            volume_planilhas+=jTxtvolumeplanilhas.getText();
    String freq_planilhas = "";
        if(jCheckBoxplanilhas.isSelected())
            freq_planilhas+= jTxtfreqplanilhas.getText();
        
    String volume_tabelas = "";
        if(jCheckBoxtabelas.isSelected())
            volume_tabelas+=jTxtvolumetabelas.getText();
    String freq_tabelas = "";
        if(jCheckBoxtabelas.isSelected())
            freq_tabelas+= jTxtfreqtabelas.getText();
        
    String volume_pdf = "";
        if(jCheckBoxpdf.isSelected())
            volume_pdf+=jTxtvolumepdf.getText();
    String freq_pdf = "";
        if(jCheckBoxpdf.isSelected())
            freq_pdf+= jTxtfreqpdf.getText();
        
    String volume_audio = "";
        if(jCheckBoxaudio.isSelected())
            volume_audio+=jTxtvolumeaudio.getText();
    String freq_audio = "";
        if(jCheckBoxaudio.isSelected())
            freq_audio+= jTxtfreqaudio.getText();
        
    String volume_texto = "";
        if(jCheckBoxtexto.isSelected())
            volume_texto+=jTxtvolumetexto.getText();
    String freq_texto = "";
        if(jCheckBoxtexto.isSelected())
            freq_texto+= jTxtfreqtexto.getText();
        
    
    Bronze usuarioluiz = new Bronze(origem, formato, sistema, volume_json, freq_json, volume_csv, 
            freq_csv, volume_planilhas, freq_planilhas, volume_tabelas, freq_tabelas, volume_pdf, 
            freq_pdf, volume_audio, freq_audio, volume_texto, freq_texto);
        
        try {
            Connection conexao = new Conexao().getConnection();
            BronzeDAO cadastro = new BronzeDAO(conexao);
            cadastro.insert(usuarioluiz);
        
        } catch (SQLException ex) {
            Logger.getLogger(FormEscopo.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBronze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBronze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBronze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBronze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBronze().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxERP;
    private javax.swing.JCheckBox jCheckBoxaudio;
    private javax.swing.JCheckBox jCheckBoxcsv;
    private javax.swing.JCheckBox jCheckBoxjson;
    private javax.swing.JCheckBox jCheckBoxoutros;
    private javax.swing.JCheckBox jCheckBoxpdf;
    private javax.swing.JCheckBox jCheckBoxplanilhas;
    private javax.swing.JCheckBox jCheckBoxtabelas;
    private javax.swing.JCheckBox jCheckBoxtexto;
    private javax.swing.JCheckBox jCheckBoxvendas;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtfreqaudio;
    private javax.swing.JTextField jTxtfreqcsv;
    private javax.swing.JTextField jTxtfreqjson;
    private javax.swing.JTextField jTxtfreqpdf;
    private javax.swing.JTextField jTxtfreqplanilhas;
    private javax.swing.JTextField jTxtfreqtabelas;
    private javax.swing.JTextField jTxtfreqtexto;
    private javax.swing.JTextField jTxtvolumeaudio;
    private javax.swing.JTextField jTxtvolumecsv;
    private javax.swing.JTextField jTxtvolumejson;
    private javax.swing.JTextField jTxtvolumepdf;
    private javax.swing.JTextField jTxtvolumeplanilhas;
    private javax.swing.JTextField jTxtvolumetabelas;
    private javax.swing.JTextField jTxtvolumetexto;
    // End of variables declaration//GEN-END:variables
}
