/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AjudaDAO;
import dao.Conexao;
import dao.UsuarioDAO;
import getset.variables;
import java.sql.Connection;
import sql.LoginController;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Ajuda;
import model.AjudaDown;
import model.GoldDown;
import model.Usuario;
import model.UsuarioUP;
import sql.crudsql;
/**
 *
 * @author Igor
 */
public class InicioSuporte extends javax.swing.JFrame {
    

    /**
     * Creates new form LoginView
     */
    public InicioSuporte() {
        initComponents();
        
        jLabel3.setVisible(false);
        jBuscaUsuario.setVisible(false);
        jButton1.setVisible(false);
        jBuscaLabel.setVisible(false);
        jLabel5.setVisible(false);
        jComboBox1.setVisible(false);
        jButton4.setVisible(false);
        
        jSuporte.setVisible(false);
        
        jAjuda.setVisible(false);
        
            
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Inicio = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jAjuda = new javax.swing.JPanel();
        labelAjudaNome = new javax.swing.JLabel();
        txtNomeAjuda = new javax.swing.JTextField();
        labelAjudaTelefone = new javax.swing.JLabel();
        txtTelefoneAjuda = new javax.swing.JFormattedTextField();
        labelAjudaEmail = new javax.swing.JLabel();
        txtEmailAjuda = new javax.swing.JTextField();
        labelAjudaMensagem = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMensagemAjuda = new javax.swing.JTextArea();
        btnAjudaEnviar = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        Perfil = new javax.swing.JPanel();
        jSuporte = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaproduto = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jNivelAcesso = new javax.swing.JLabel();
        jNivelAcesso0 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBuscaUsuario = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jBuscaLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        background1 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        jMenuNovo = new javax.swing.JMenuItem();
        jMenuCadastros = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        Inicio.setLayout(null);

        jButton10.setText("Ajuda");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        Inicio.add(jButton10);
        jButton10.setBounds(20, 10, 61, 23);

        jAjuda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jAjuda.setLayout(null);

        labelAjudaNome.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        labelAjudaNome.setForeground(new java.awt.Color(240, 240, 240));
        labelAjudaNome.setText("Nome: ");
        jAjuda.add(labelAjudaNome);
        labelAjudaNome.setBounds(290, 160, 60, 21);

        txtNomeAjuda.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtNomeAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAjudaActionPerformed(evt);
            }
        });
        jAjuda.add(txtNomeAjuda);
        txtNomeAjuda.setBounds(360, 160, 600, 40);

        labelAjudaTelefone.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        labelAjudaTelefone.setForeground(new java.awt.Color(240, 240, 240));
        labelAjudaTelefone.setText("Telefone: ");
        jAjuda.add(labelAjudaTelefone);
        labelAjudaTelefone.setBounds(270, 210, 80, 30);

        txtTelefoneAjuda.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtTelefoneAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneAjudaActionPerformed(evt);
            }
        });
        jAjuda.add(txtTelefoneAjuda);
        txtTelefoneAjuda.setBounds(360, 210, 600, 40);

        labelAjudaEmail.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        labelAjudaEmail.setForeground(new java.awt.Color(240, 240, 240));
        labelAjudaEmail.setText("E-mail: ");
        jAjuda.add(labelAjudaEmail);
        labelAjudaEmail.setBounds(280, 260, 64, 30);

        txtEmailAjuda.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jAjuda.add(txtEmailAjuda);
        txtEmailAjuda.setBounds(360, 260, 600, 40);

        labelAjudaMensagem.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        labelAjudaMensagem.setForeground(new java.awt.Color(240, 240, 240));
        labelAjudaMensagem.setText("Mensagem: ");
        jAjuda.add(labelAjudaMensagem);
        labelAjudaMensagem.setBounds(250, 330, 100, 30);

        txtMensagemAjuda.setColumns(20);
        txtMensagemAjuda.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtMensagemAjuda.setRows(5);
        jScrollPane2.setViewportView(txtMensagemAjuda);

        jAjuda.add(jScrollPane2);
        jScrollPane2.setBounds(360, 340, 600, 140);

        btnAjudaEnviar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnAjudaEnviar.setText("Enviar");
        btnAjudaEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaEnviarActionPerformed(evt);
            }
        });
        jAjuda.add(btnAjudaEnviar);
        btnAjudaEnviar.setBounds(870, 500, 90, 30);

        jButton11.setText("Voltar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jAjuda.add(jButton11);
        jButton11.setBounds(1060, 20, 61, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/dom-rock2.png"))); // NOI18N
        jAjuda.add(jLabel7);
        jLabel7.setBounds(10, 10, 1150, 550);

        Inicio.add(jAjuda);
        jAjuda.setBounds(50, 40, 1170, 570);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/dom-rock.png"))); // NOI18N
        background.setText("jLabel1");
        Inicio.add(background);
        background.setBounds(0, 0, 1280, 700);

        jTabbedPane1.addTab("Inicio", Inicio);

        Perfil.setLayout(null);

        jSuporte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jSuporte.setForeground(new java.awt.Color(255, 255, 255));
        jSuporte.setLayout(null);

        tabelaproduto.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tabelaproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "E-mail", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaproduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaprodutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaproduto);

        jSuporte.add(jScrollPane1);
        jScrollPane1.setBounds(650, 10, 450, 510);

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel4.setText("Mensagem:");
        jSuporte.add(jLabel4);
        jLabel4.setBounds(220, 30, 170, 28);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jSuporte.add(jTextField1);
        jTextField1.setBounds(29, 70, 600, 450);

        jButton8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton8.setText("Atualizar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jSuporte.add(jButton8);
        jButton8.setBounds(533, 20, 90, 23);

        jButton9.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton9.setText("Fechar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jSuporte.add(jButton9);
        jButton9.setBounds(450, 20, 80, 23);

        Perfil.add(jSuporte);
        jSuporte.setBounds(80, 60, 1110, 540);

        jNivelAcesso.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jNivelAcesso.setForeground(new java.awt.Color(255, 255, 255));
        jNivelAcesso.setText("Nivel de Acesso:");
        Perfil.add(jNivelAcesso);
        jNivelAcesso.setBounds(30, 110, 200, 28);

        jNivelAcesso0.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jNivelAcesso0.setForeground(new java.awt.Color(255, 255, 255));
        jNivelAcesso0.setText("Suporte");
        Perfil.add(jNivelAcesso0);
        jNivelAcesso0.setBounds(240, 110, 300, 28);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pesquisar usuario:");
        Perfil.add(jLabel3);
        jLabel3.setBounds(40, 300, 230, 30);

        jBuscaUsuario.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        Perfil.add(jBuscaUsuario);
        jBuscaUsuario.setBounds(240, 300, 230, 30);

        jComboBox1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Usuario", "Suporte", "Administrador" }));
        Perfil.add(jComboBox1);
        jComboBox1.setBounds(330, 360, 120, 30);

        jBuscaLabel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jBuscaLabel.setForeground(new java.awt.Color(255, 255, 255));
        jBuscaLabel.setText("Usuario:   - - - - - - - - - -");
        Perfil.add(jBuscaLabel);
        jBuscaLabel.setBounds(40, 370, 220, 21);

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nivel");
        Perfil.add(jLabel5);
        jLabel5.setBounds(270, 370, 60, 21);

        jButton1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Perfil.add(jButton1);
        jButton1.setBounds(480, 300, 90, 23);

        jButton4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton4.setText("Atualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Perfil.add(jButton4);
        jButton4.setBounds(470, 360, 110, 30);

        jButton5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton5.setText("Ver mais...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Perfil.add(jButton5);
        jButton5.setBounds(40, 200, 100, 23);

        jButton6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton6.setText("Logout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Perfil.add(jButton6);
        jButton6.setBounds(850, 20, 73, 23);

        jButton7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton7.setText("Ver pedidos de Suporte");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Perfil.add(jButton7);
        jButton7.setBounds(170, 200, 210, 23);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/dom-rock.png"))); // NOI18N
        background1.setText("jLabel1");
        Perfil.add(background1);
        background1.setBounds(0, 250, 1280, 700);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/dom-rock2.png"))); // NOI18N
        background2.setText("jLabel1");
        background2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background2.setMaximumSize(new java.awt.Dimension(1280, 720));
        background2.setMinimumSize(new java.awt.Dimension(1280, 720));
        background2.setPreferredSize(new java.awt.Dimension(1280, 720));
        Perfil.add(background2);
        background2.setBounds(0, 0, 1280, 700);

        jTabbedPane1.addTab("Perfil", Perfil);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 1280, 700);

        jMenuBar1.setForeground(new java.awt.Color(102, 102, 102));

        jMenuClientes.setForeground(new java.awt.Color(51, 51, 51));
        jMenuClientes.setText("Clientes");
        jMenuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuClientesMouseClicked(evt);
            }
        });

        jMenuNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuNovo.setText("Novo");
        jMenuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovoActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuNovo);

        jMenuCadastros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuCadastros.setText("Cadastrados");
        jMenuCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCadastrosMouseClicked(evt);
            }
        });
        jMenuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrosActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuCadastros);

        jMenuBar1.add(jMenuClientes);

        jMenu3.setText("Sair");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        crudsql crud = new crudsql();
        UsuarioUP us = new UsuarioUP();
        crud.mostrarUsuario(jBuscaUsuario.getText());
        jBuscaLabel.setText("Usuario: "+us.getUsuario());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        crudsql crud = new crudsql();
        UsuarioUP objvar = new UsuarioUP();

        objvar.setUsuario(jBuscaUsuario.getText());
        objvar.setNivelAcesso((String) jComboBox1.getSelectedItem());
        crud.atualizarUsuario(objvar.getUsuario(), objvar.getNivelAcesso());
        jLabel3.setVisible(false);
        jBuscaUsuario.setVisible(false);
        jButton1.setVisible(false);
        jBuscaLabel.setVisible(false);
        jLabel5.setVisible(false);
        jComboBox1.setVisible(false);
        jButton4.setVisible(false);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String nivelacesso = "Administrador";
        if(jNivelAcesso0.getText().equals(nivelacesso)){
            jLabel3.setVisible(true);
            jBuscaUsuario.setVisible(true);
            jButton1.setVisible(true);
            jBuscaLabel.setVisible(true);
            jLabel5.setVisible(true);
            jComboBox1.setVisible(true);
            jButton4.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Seu nivel de acesso não confere a esta função.","Acesso Negado",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        LoginView in = new LoginView();
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String nivelacesso = "Usuario";
        
        if(jNivelAcesso0.getText().equals(nivelacesso)){
            JOptionPane.showMessageDialog(null,"Seu nivel de acesso não confere a esta função.","Acesso Negado",JOptionPane.INFORMATION_MESSAGE);
        }else{
        crudsql crud = new crudsql();
        crud.mostrarAjuda(jBuscaUsuario.getText());
        
        List<AjudaDown> empresas = crud.getHelp();
        DefaultTableModel tabelaProduto =
                (DefaultTableModel)tabelaproduto.getModel();
        
        tabelaProduto.setRowCount(0);
        
        
        
        for(int i=0; i<empresas.size(); i++ ) {  
            tabelaProduto.insertRow(i, empresas.get(i).getNovoProduto());
        }
        jSuporte.setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        crudsql crud = new crudsql();
        crud.mostrarAjuda(jBuscaUsuario.getText());
        
        List<AjudaDown> empresas = crud.getHelp();
        DefaultTableModel tabelaProduto =
                (DefaultTableModel)tabelaproduto.getModel();
        
        tabelaProduto.setRowCount(0);
        
        
        
        for(int i=0; i<empresas.size(); i++ ) {  
            tabelaProduto.insertRow(i, empresas.get(i).getNovoProduto());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tabelaprodutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaprodutoMouseClicked
        AjudaDown var = new AjudaDown();
        crudsql crud = new crudsql();
        crud.mostrarAjuda(jBuscaUsuario.getText());
        
        jTextField1.setText(var.getMensagem());
    }//GEN-LAST:event_tabelaprodutoMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jSuporte.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrosActionPerformed
        // TODO add your handling code here:
        String admin = "Administrador";
        String sup = "Suporte";
        String user = "Usuario";

        if(jNivelAcesso0.getText().equals(admin)){
            Mostrar adm = new Mostrar();
            adm.setVisible(true);
            dispose();
        }
        if(jNivelAcesso0.getText().equals(sup)){
            MostrarSuporte suport  = new MostrarSuporte();
            suport.setVisible(true);
            dispose();
        }
        if(jNivelAcesso0.getText().equals(user)){
            MostrarUsuario usuario = new MostrarUsuario();
            usuario.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_jMenuCadastrosActionPerformed

    private void jMenuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovoActionPerformed
        // TODO add your handling code here:
        EtapasSuporte is = new EtapasSuporte();
        is.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuNovoActionPerformed

    private void jMenuCadastrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCadastrosMouseClicked
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jMenuCadastrosMouseClicked

    private void jMenuClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuClientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuClientesMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void txtNomeAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAjudaActionPerformed

    private void txtTelefoneAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneAjudaActionPerformed

    private void btnAjudaEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaEnviarActionPerformed
        if(txtNomeAjuda.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo Nome é obrigatório, favor preencher", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(txtTelefoneAjuda.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo Telefone é obrigatório, favor preencher", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(txtEmailAjuda.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo Email é obrigatório, favor preencher", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(txtMensagemAjuda.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo Mensagem é obrigatório, favor preencher", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String nome = txtNomeAjuda.getText();
        String telefone = txtTelefoneAjuda.getText();
        String mensagem = txtMensagemAjuda.getText();
        String email = txtEmailAjuda.getText();

        Ajuda usuarioluiz = new Ajuda(nome, telefone, email, mensagem);

        try {
            Connection conexao = new Conexao().getConnection();
            AjudaDAO cadastro = new AjudaDAO(conexao);
            cadastro.insert(usuarioluiz);
            JOptionPane.showMessageDialog(null, "Mensagem enviada.", "Suporte", JOptionPane.ERROR_MESSAGE);

        } catch (SQLException ex) {
            Logger.getLogger(AjudaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAjudaEnviarActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jAjuda.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jAjuda.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSuporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSuporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSuporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSuporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSuporte().setVisible(true);
            }
        });
    }


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel Perfil;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JButton btnAjudaEnviar;
    private javax.swing.JPanel jAjuda;
    private javax.swing.JLabel jBuscaLabel;
    private javax.swing.JTextField jBuscaUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastros;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenuItem jMenuNovo;
    private javax.swing.JLabel jNivelAcesso;
    private javax.swing.JLabel jNivelAcesso0;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jSuporte;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelAjudaEmail;
    private javax.swing.JLabel labelAjudaMensagem;
    private javax.swing.JLabel labelAjudaNome;
    private javax.swing.JLabel labelAjudaTelefone;
    private javax.swing.JTable tabelaproduto;
    private javax.swing.JTextField txtEmailAjuda;
    private javax.swing.JTextArea txtMensagemAjuda;
    private javax.swing.JTextField txtNomeAjuda;
    private javax.swing.JFormattedTextField txtTelefoneAjuda;
    // End of variables declaration//GEN-END:variables

    public Object getjTextField1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Object Ancora() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Object getAncora() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
